### ISSUE TITLE
Fail to generate a KeyPair with the given options

### ISSUE THREAD

**Issue by mohamm6d** [Daanra/laravel-lets-encrypt#1]
After installing the library, it gives this error on local! not tested on staging yet. 
AcmePhp\Ssl\Exception\KeyPairGenerationException
Fail to generate a KeyPair with the given options

\vendor\acmephp\ssl\Generator\KeyPairGenerator.php:68

**Comment by Daanra** [comment]
Hey,

Thank you for your report.

I'm guessing if you run this line of code:
```php
(new \AcmePhp\Ssl\Generator\KeyPairGenerator())->generateKeyPair();
```
you get the same error.

Maybe you haven't installed [OpenSSL](https://www.php.net/manual/en/book.openssl.php)?

If you have, you can find the underlying error by doing something along the lines of:
```php
(new AcmePhp\Ssl\Generator\RsaKey\RsaKeyGenerator())->generatePrivateKey(new \AcmePhp\Ssl\Generator\RsaKey\RsaKeyOption());
```
This line should throw another exception with a more elaborate error message.

**Comment by mohamm6d** [comment]
Yes, you are right. need to setup openssl on local. Works perfectly on production however verification process needs some improvements :)
