### ISSUE TITLE
In which php version this package was tested?

### ISSUE THREAD

**Issue by abublihi** [Daanra/laravel-lets-encrypt#12]
Hi, thank you fro the awesome package.

I have tried to install the package in laravel 5.5 project but not working. so i am wondering in which php version it was tested?

if you wondering what the errors:
`PHP Error:  Call to undefined method Daanra/LaravelLetsEncrypt/Jobs/RegisterAccount::dispatchNow()`
second error 
`BadMethodCallException with message 'Method ensureDirectoryExists does not exist.`

**Comment by Daanra** [comment]
@abublihi Which version are you using? v0.2.4 or the beta version v0.3.0? If you're using 0.3.0, please switch to 0.2.4.

**Comment by abublihi** [comment]
Than you for the quick response,

Iam using 2.4 with laravel 5.5, so I have to update to laravel 5.6.

Yes please update the requirements in `composer.json`
