### ISSUE TITLE
Does it work with 8.6+?

### ISSUE THREAD

**Issue by jawwadkalia** [Daanra/laravel-lets-encrypt#13]
Getting an issue installing in on a fresh laravel 8.65 installation (installing all dependencies) - is it compatible?

**Comment by Dasinfomedia2** [comment]
on which laravel version does it work properly?

**Comment by Daanra** [comment]
Should work if you downgrade Guzzle to ^6.0. 

For example:
```
laravel new test
cd test
composer require daanra/laravel-lets-encrypt guzzlehttp/guzzle:^6.0  -w
```

To support guzzle^7.0, we need to wait for https://github.com/acmephp/core to update their dependencies.

Let me know if you still have some problems.
