### ISSUE TITLE
Support for laravel 9 and php 8

### ISSUE THREAD

**Issue by manuelfrans** [Daanra/laravel-lets-encrypt#17]
Kindly add support for laravel 9 & php 8

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acmephp/core[dev-master, 1.3.0] require guzzlehttp/psr7 ^1.0 -> found guzzlehttp/psr7[1.0.0, ..., 1.x-dev] but the package is fixed to 2.2.1 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - acmephp/core 1.2.0 requires guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.0.1).
    - daanra/laravel-lets-encrypt v0.2.4 requires acmephp/core ^1.2|dev-master -> satisfiable by acmephp/core[dev-master, 1.2.0, 1.3.0].
    - Root composer.json requires daanra/laravel-lets-encrypt ^0.2.4 -> satisfiable by daanra/laravel-lets-encrypt[v0.2.4].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require daanra/laravel-lets-encrypt:*" to figure out if any version is installable, or "composer require daanra/laravel-lets-encrypt:^2.1" if you know which you need.

**Comment by Daanra** [comment]
Did you try running:
```
composer require daanra/laravel-lets-encrypt guzzlehttp/guzzle:^6.0  -w
```
?

**Comment by renky** [comment]
same problem - yes I tried - but then there are much more problems open due to packages that require guzzlehttp/psr7 in version 2 and upwards...
Unfortunatelly I think daanra cannot solve it, sind acmephp/core requires "guzzlehttp/psr7": "^1.0",

**Comment by manuelfrans** [comment]
> Did you try running:
> 
> ```
> composer require daanra/laravel-lets-encrypt guzzlehttp/guzzle:^6.0  -w
> ```
> 
> ?

Yeah I did . still fails. I switched from Nginx to caddy for this purpose. provides on demand ssl

**Comment by Daanra** [comment]
Should be fixed now in `dev-master`. Will release it later.

Let me know if you still run into any issues.
