### ISSUE TITLE
Scope problem when running renew from a callback

### ISSUE THREAD

**Issue by kristijan97** [Daanra/laravel-lets-encrypt#19]
I am struggling to find a solution for a scope problem in the Laravel when you execute the command from the callback. From the Laravel command, I am trying to execute the job in a different context (multi-tenant platform, changing database and other settings). However, no matter what I tried, I all the time getting the error from the package. Reading through PHP manuals, StackOverflow and other articles, I tried bunch of different things such as:
- callable (https://www.php.net/manual/en/language.types.callable.php, [How to call the callable function in PHP?](https://stackoverflow.com/questions/28606774/how-to-call-the-callable-function-in-php))
- passing $this ([Is there a workaround for $this within a closure in PHP 5.3?](https://stackoverflow.com/questions/21305344/is-there-a-workaround-for-this-within-a-closure-in-php-5-3))
- passing $this by reference etc.
However, none of these approaches worked in this case. What do you think that's causing this problem?

**I must emphasize that I do not have a problem with scope in general - I have numerous commands which are executed in a dynamic context and everything runs without any problem. This error occurs only when I try to use this package in a callback**

**Expected result:** Running job in correct Laravel context (changed by setup method in Instance model).

**Actual result:**
> Using $this when not in object context
>   at app/Models/Instance.php:80

Let me show you the problem:

_Command:_
```php
class RenewExpiringCertificates extends Command {
  public function handle(): int {
      LetsEncryptCertificate::query()
          ->requiresRenewal()
          ->chunk(100, function (LetsEncryptCertificateCollection $certificates) {
              $certificates->renewNow();  // PROBLEMATIC CALL
          });

      return 0;
  }
  
  protected function execute(InputInterface $input, OutputInterface $output) {
      $method = method_exists($this, 'handle') ? 'handle' : '__invoke';

      $count = 0;
      Instance::inAllActiveSpaces(function () use ($method, &$count) {
          $count += $this->laravel->call([$this, $method]); // CALL TO HANDLE METHOD
      });

      return $count;
  }
}
```

_Instance:_
```php
class Instance extends Model {
    protected $connection = 'mysql-master';

    public function setup() {
        Config::set('database.connections.mysql.database', $this->database);
        DB::reconnect('mysql');
        // ...
    }

    public static function inAllActiveSpaces($callback) {
        Instance::active()->each(function ($instance) use ($callback) {
            $instance->setup();
            $callback($instance);  // BREAKING POINT
        });
    }
}
```

From my research and looking into the source code, this looks to raise a problem:
```php
// Daanra\LaravelLetsEncrypt\Models\LetsEncryptCertificate
public function renewNow(): self
{
    return LetsEncrypt::renewNow($this);
}
```

**Comment by Daanra** [comment]
Any chance you could provide a minimal repository for error reproduction?

**Comment by kristijan97** [comment]
Hi man, sorry for keeping you waiting. I had a wedding this weekend and I was really tired. I created really minimal demo here:
https://github.com/kristijan97/CertExample

Please take a look and tell me what you think. Thank you in advance!

**Comment by Daanra** [comment]
The error you're getting seems to come specifically from your error handling:
```php
try {
        $callback($instance);
} catch (\Exception $e) {
        $this->error($e->getMessage()); // <== this is the culprit
}
```

Try changing this to just:
```php
$callback($instance);
```

Then you'll get a more appropriate error. In this case, it's that LetsEncrypt won't issue an SSL certificate for a `.test` domain.

Closing this for now. Feel free to reopen if you're still having issues after this.
