### ISSUE TITLE
Certificate not creating please help me

### ISSUE THREAD

**Issue by mmejaz786** [Daanra/laravel-lets-encrypt#20]
root@files:/home/fs/public_html# php artisan lets-encrypt:create -d edulife.cmhlmc.com
Generating certificates for 1 domains.
edulife.cmhlmc.com:
Failed to generate a certificate for edulife.cmhlmc.com
Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"66.45.249.26: Invalid response from http:\/\/edulife.cmhlmc.com\/.well-known\/acme-challenge\/qCfxYAtN2NeQPm5WT1EIPTO5DBOX_u9YW3pp8VxChao: 404","status":403},"url":"https:\/\/acme-staging-v02.api.letsencrypt.org\/acme\/chall-v3\/3123418344\/UPLhFg","token":"qCfxYAtN2NeQPm5WT1EIPTO5DBOX_u9YW3pp8VxChao","validationRecord":[{"url":"http:\/\/edulife.cmhlmc.com\/.well-known\/acme-challenge\/qCfxYAtN2NeQPm5WT1EIPTO5DBOX_u9YW3pp8VxChao","hostname":"edulife.cmhlmc.com","port":"80","addressesResolved":["66.45.249.26"],"addressUsed":"66.45.249.26"}],"validated":"2022-07-25T10:12:37Z"}).

**Comment by Daanra** [comment]
It says that it couldn't find the challenge on `http://edulife.cmhlmc.com/.well-known/acme-challenge/qCfxYAtN2NeQPm5WT1EIPTO5DBOX_u9YW3pp8VxChao`.

Do you have a route that does something like this:
```php
Route::get('/.well-known/acme-challenge/{token}', function (string $token) {
    return \Illuminate\Support\Facades\Storage::get('public/.well-known/acme-challenge/' . $token);
})
```
?

**Comment by mmejaz786** [comment]
**Thank you Daanra** for replying. let me elaborate the scenario that I am using  I have a fs.***.com domain and I installed the package on it for create the SSL certificate for other my different domain that also are hosted on the same server. But when I am trying to create the certificate this error message is showing me and I also defined the following route that you asked me in your previous message. it is defined my fs.***.com 's route file.

Route::get('/.well-known/acme-challenge/{token}', function (string $token) {
    return \Illuminate\Support\Facades\Storage::get('public/.well-known/acme-challenge/' . $token);
});

**Comment by Daanra** [comment]
So have you added the route to a different web app than the one that serves `edulife.cmhlmc.com`?

That won't work. You need to ensure that the `http://edulife.cmhlmc.com/.well-known/acme-challenge/{token}` url returns the token stored on disk.

**Comment by mmejaz786** [comment]
i have add this route into edulif.cmhlmc.com domain that is hosted on the same server

Route::get('/.well-known/acme-challenge/{token}', function (string $token) {
    return \Illuminate\Support\Facades\Storage::get('public/.well-known/acme-challenge/' . $token);
});
when i am trying to create the certification by this command

php artisan lets-encrypt:create -d doamin_name

is it sowing me the same error message.

root@files:/home/fs/public_html# php artisan lets-encrypt:create -d beta.cmhlmc.com
Generating certificates for 1 domains.
beta.cmhlmc.com:
Failed to generate a certificate for beta.cmhlmc.com
Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","deta                                    il":"216.158.227.126: Invalid response from http:\/\/beta.cmhlmc.com\/.well-known\/acme-challenge\/teQFa522NVkkQEsakQVrV91Lx1Azy                                    eNpQ9jxvWvrJ_w: 500","status":403},"url":"https:\/\/acme-staging-v02.api.letsencrypt.org\/acme\/chall-v3\/3217483044\/FZpVVQ","t                                    oken":"teQFa522NVkkQEsakQVrV91Lx1AzyeNpQ9jxvWvrJ_w","validationRecord":[{"url":"http:\/\/beta.cmhlmc.com\/.well-known\/acme-chal                                    lenge\/teQFa522NVkkQEsakQVrV91Lx1AzyeNpQ9jxvWvrJ_w","hostname":"beta.cmhlmc.com","port":"80","addressesResolved":["216.158.227.1                                    26"],"addressUsed":"216.158.227.126"}],"validated":"2022-08-03T06:34:02Z"}).

**Comment by Daanra** [comment]
Try navigating to the URL in the error: http://beta.cmhlmc.com/.well-known/acme-challenge/teQFa522NVkkQEsakQVrV91Lx1AzyeNpQ9jxvWvrJ_w

You will see that instead of returning the challenge, it returns a 500 error.

This is unrelated to the library itself.

**Comment by mmejaz786** [comment]
i have changed the permission now its still showing the same error message.

Failed to generate a certificate for beta.cmhlmc.com
Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"216.158.227.126: Invalid response from http:\/\/beta.cmhlmc.com\/.well-known\/acme-challenge\/k31zXYgM-kWvI9xUVbJdyzQO055wdyuRTbm7my_ocjQ: 500","status":403},"url":"https:\/\/acme-staging-v02.api.letsencrypt.org\/acme\/chall-v3\/3226941914\/vGVfdg","token":"k31zXYgM-kWvI9xUVbJdyzQO055wdyuRTbm7my_ocjQ","validationRecord":[{"url":"http:\/\/beta.cmhlmc.com\/.well-known\/acme-challenge\/k31zXYgM-kWvI9xUVbJdyzQO055wdyuRTbm7my_ocjQ","hostname":"beta.cmhlmc.com","port":"80","addressesResolved":["216.158.227.126"],"addressUsed":"216.158.227.126"}],"validated":"2022-08-04T04:47:24Z"}).

**Comment by Daanra** [comment]
Could be because of non-default settings in `config/filesystems.php`.

Validate where your challenge is placed on disk (should be in `storage/app/.well-known/acme-challenge`) but this can be different depending on your filesystems settings.

You might have to specify a custom disk or path generator in the `config/lets_encrypt.php` file.
