### ISSUE TITLE
Pb with jobs

### ISSUE THREAD

**Issue by alexandre30290** [Daanra/laravel-lets-encrypt#21]
Hello,

I don't understand how create jobs after successfully generate certificate.
For example, I would like to create an apache virtualhost and add a row in database.
I found this on website but I don't understand where is this job ?

[$certificate, $pendingDispatch] = \Daanra\LaravelLetsEncrypt\Facades\LetsEncrypt::create('mydomain.com', [
    new CreateNewApacheVirtualHost('mydomain.com'), 
    new ReloadApache(),
    new NotifyUserOfNewCertificate(request()->user()),
]);

Where is job CreateNewApacheVirtualHost ? How create this please ?

**Comment by Daanra** [comment]
> Where is job CreateNewApacheVirtualHost ? How create this please ?

The `CreateNewApacheVirtualHost` is an example Job that you will have to implement yourself. See also https://github.com/Daanra/laravel-lets-encrypt/issues/7

You could for example create a job that does something along the lines of:
```php
public function handle()
{
        // Configure the apache disk yourself
        Storage::disk('apache')->put($myDomainName.'.conf', $configForVirtualHost);
        $process = new Process(['a2ensite', $myDomainName]);
        if ($process->run() !== 0) {
            throw new \Exception('Failed to run a2ensite for '.$myDomainName);
        }
}
```

**Comment by Muffinman** [comment]
Note that this most likely requires PHP command to be executed as root.
