### ISSUE TITLE
[Feature Request] Subject Alternative Names

### ISSUE THREAD

**Issue by Muffinman** [Daanra/laravel-lets-encrypt#22]
Hi,

I'm wondering if this package supports sending `SubjectAlternativeNames` to LetsEncrypt / AcmePHP?

I can see that AcmePHP itself [does have support for them](https://acmephp.github.io/documentation/guides/multidomain-certificates.html), but I couldn't see any obvious references in this package.

EDIT: Our use case is for a multi-tenant Laravel application. we want one vhost per tenant rather than one per domain, so it makes sense to have a single SSL cert with all their active domains contained inside.

**Comment by Daanra** [comment]
It currently does not support SubjectAlternativeNames but this should be rather easy to implement. 

I can probably release this in a couple of days.

**Comment by Muffinman** [comment]
That sounds excellent! Happy to send a PR or collaborate on this if it makes sense.

I did take a look but I couldn't see any way of doing it without breaking changes. I think it will need new parameters adding to methods.

**Comment by Daanra** [comment]
Feature added to [v0.5.0](https://github.com/Daanra/laravel-lets-encrypt/releases/tag/v.0.5.0)
