### ISSUE TITLE
Does this work for internally used domains that are not accessible by networks outside of our own network

### ISSUE THREAD

**Issue by XavegX367** [Daanra/laravel-lets-encrypt#26]
I was wondering if it is possible o use this package to create SSL certificates for internally used domains that are not accessible from outside of our network. The domain is set using our own local DNS Server.

Right now when I try to create a certificate it returns the following:

Challenge failed (response: {"type":"http-01","status":"invalid","error":{"type":"urn:ietf:params:acme:error:unauthorized","detail":"91.184.0.100: Invalid response from http:\/\/labelsolutions..........nl\/.well-known\/acme-challenge\/w9Js1qFOMkH9LH2Bp6jTJBZFNq79KM0ehuHuJ92MSd0: 404","status":403},"url":"https:\/\/acme-v02.api.letsencrypt.org\/acme\/chall-v3\/174525676347\/Y0Wtbw","token":"w9Js1qFOMkH9LH2Bp6jTJBZFNq79KM0ehuHuJ92MSd0","validationRecord":[{"url":"http:\/\/labelsolutions............nl\/.well-known\/acme-challenge\/w9Js1qFOMkH9LH2Bp6jTJBZFNq79KM0ehuHuJ92MSd0","hostname":"labelsolutions..........nl","port":"80","addressesResolved":["91.184.0.100"],"addressUsed":"91.184.0.100"}],"validated":"2022-11-10T09:56:36Z"}).

I replaced the original domain name for dots, but the url for us internally is working.

**Comment by XavegX367** [comment]
Sidenote: I am running this from 'domains........nl' so the tokens get stored in the domains storage but it seems like it wants to retrieve it from labelsolutions..........nl

**Comment by Daanra** [comment]
> I was wondering if it is possible o use this package to create SSL certificates for internally used domains that are not accessible from outside of our network.

This is not possible. Let's Encrypt's server needs to be able to fetch a token from the domain for which you're issuing a certificate.
