### ISSUE TITLE
Issue with newest migration under MySQL

### ISSUE THREAD

**Issue by jayo-exe** [Daanra/laravel-lets-encrypt#29]
The latest updates added a migration to add a new `subject_alternative_names` field to the certificates table.  However, mySQL does not allow default values for JSON fields, so running this migration can not succeed:

`BLOB, TEXT, GEOMETRY or JSON column 'subject_alternative_names' can't have a default value`

When modifying the migration file to remove the default value declaration, the migration succeeds, but Certificate Requests fail because the code is expecting an empty array in this field:

`TypeError: Argument 8 passed to Daanra\LaravelLetsEncrypt\AcmePhp\Ssl\DistinguishedName::__construct() must be of the type array, null given, called in /home/forge/[redacted]/vendor/daanra/laravel-lets-encrypt/src/Jobs/RequestCertificate.php on line 41`

**Comment by Daanra** [comment]
Issues with Postgres now: https://github.com/Daanra/laravel-lets-encrypt/pull/31#issuecomment-1487985386
