### ISSUE TITLE
Error with confirmation.

### ISSUE THREAD

**Issue by VoronVoronov** [Daanra/laravel-lets-encrypt#3]
When generating SSL, an error is displayed that it is impossible to confirm and the link is in this https://demo.ru/.well-known/acme-challenge/mfWca8xsOPwcgHHTsPwit0xE0zvvXNoZLOx-JMTJsrs

But if you try
https://demo.ru/public/storage/.well-known/acme-challenge/mfWca8xsOPwcgHHTsPwit0xE0zvvXNoZLOx-JMTJsrs

Then everything turns out perfectly. How to fix it?

**Comment by VoronVoronov** [comment]
When trying to execute a command via artisan https://prnt.sc/172f7va

**Comment by Daanra** [comment]
You can try adding a route that returns the challenge:
```php
Route::get('/.well-known/acme-challenge/{token}', function (string $token) {
     return \Illuminate\Support\Facades\Storage::get('public/.well-known/acme-challenge/' . $token);
 })
 ```
