### ISSUE TITLE
Renew issue

### ISSUE THREAD

**Issue by trilochan90** [Daanra/laravel-lets-encrypt#32]
Hi, 
I am getting the below issue while renewing the certificate, kindly suggest the solution

Argument 2 passed to AcmePhp\Core\AcmeClient::registerAccount() must be an instance of AcmePhp\Core\Protocol\ExternalAccount or null, string given, called in /var/www/html/typof/vendor/daanra/laravel-lets-encrypt/src/Jobs/RegisterAccount.php on line 27

**Comment by Daanra** [comment]
What version are you using?

Seems like you are using an older version. You might want to update to the latest version
